config/routes.rb
Rails.application.routes.draw do
  get 'reservation/:reservation_id/braintree/new' => "braintree#new", as: "braintree_new"
  get 'welcome/index'
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings

  resources :listings do
    resources :reservations
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/mylistings" => "listings#my_listings", as: "my_listings"
  get "/listings/:id/verify" => "listings#verify_listing", as: "verify_listing"

  post "/reservation/:id/braintree/checkout" => "braintree#checkout", as: "total_price_braintree_checkout" 
end

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :user
    has_many :reservations, dependent: :destroy
    mount_uploaders :images, ImageUploader

    scope :omnisearch, -> (query) { where(" property_name ILIKE ? or property_type ILIKE ? or city ILIKE ? OR country ILIKE ? ", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%") }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :verify_action, only: [:verify_listing]
    
    def index
        @listings = Listing.all.order("property_name").page params[:page]
        
        
        @listings = Listing.where(nil)
        filtering_params(params).each do |key, value|
            @listings = @listings.public_send(key, value) if value.present?                       
            #  this is what the above line does
            #   @listings.key(value)
            #   eg. @listing.omisearch(malaysia)
        end

        respond_to do |format|
            format.html
            format.js
        end
    end
    
    def show
        @listing = Listing.find(params[:id])
        @reservation = Reservation.new
    end

    def new
        @listing = Listing.new
    end

    def edit
        @listing = Listing.find(params[:id])
    end

    def create
        @listing = Listing.new(listing_params)
        @listing.user_id = current_user.id

        if @listing.save
            redirect_to @listing
        else
            render 'new'
        end
    end

    def update
        @listing = Listing.find(params[:id])

        if @listing.update(listing_params)
            redirect_to @listing
        else
            render 'edit'
        end
    end

    def destroy
        @listing = Listing.find(params[:id])
        @listing.destroy
        redirect_to listings_path
    end

    def verify_listing
        @listing = Listing.find(params[:id])
        @listing.update(verification: true)
        flash[:notice] = "Property successfully verified."
        return redirect_to listings_path      
    end

    def my_listings
        @listings = current_user.listings
    end
    
    private
    def listing_params
        params.require(:listing).permit(
            :property_type, 
            :property_name, 
            :no_of_guests, 
            :no_of_bedrooms, 
            :no_of_beds, 
            :no_of_bathrooms, 
            :amenities, 
            :price_per_night, 
            :country, 
            :state, 
            :city, 
            :zipcode, 
            :address, 
            {images: []}
        )
    end

    # If the user is a customer and the listing does not belong to them:
    def verify_action
        if current_user.customer?
            redirect_to root_url
        end
    end

    # A list of the param names that can be used for filtering the Product list
    def filtering_params(params)
        params.slice(:omnisearch)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with model: @listing, :html => {:multipart => true}, local: true do |form| %>

    <% if @listing.errors.any? %>
        <div id="error_explanation">
        <h2>
            <%= pluralize(@listing.errors.count, "error") %> prohibited
            this listing from being saved:
        </h2>
        <ul>
            <% @listing.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    
    <div class="form-group row">
        <div class="form-group col-md-6">
            <%= form.label :property_type %>
            <%= form.text_field :property_type, class: 'form-control' %>
        </div>
        <div class="form-group col-md-6">
            <%= form.label :property_name %>
            <%= form.text_field :property_name, class: 'form-control' %>
        </div>
    </div>
    
    <div class="form-group row">
        <div class="form-group col-md-3">
            <%= form.label :country %>
            <%= form.text_field :country, class: 'form-control' %>
        </div>
        <div class="form-group col-md-3">
            <%= form.label :state %>
            <%= form.text_field :state, class: 'form-control' %>
        </div>
        <div class="form-group col-md-3">
            <%= form.label :city %>
            <%= form.text_field :city, class: 'form-control' %>
        </div>
        <div class="form-group col-md-3">
            <%= form.label :zipcode %>
            <%= form.text_field :zipcode, class: 'form-control' %>
        </div>
    </div>

    <div class="form-group row ">
        <div class="form-group col-md-12">
            <%= form.label :address %>
            <%= form.text_field :address, class: 'form-control' %>
        </div>
    </div>

    <div class="form-group row">
        <div class="form-group col-md-3">
            <%= form.label :no_of_guests %>
            <%= form.text_field :no_of_guests, class: 'form-control' %>
        </div>
        <div class="form-group col-md-3">
            <%= form.label :no_of_bedrooms %>
            <%= form.text_field :no_of_bedrooms, class: 'form-control' %>
        </div>
        <div class="form-group col-md-3">
            <%= form.label :no_of_beds %>
            <%= form.text_field :no_of_beds, class: 'form-control' %>
        </div>
        <div class="form-group col-md-3">
            <%= form.label :no_of_bathrooms %>
            <%= form.text_field :no_of_bathrooms, class: 'form-control' %>
        </div>
    </div>

    <div class="form-group row">
        <div class="form-group col-md-12">
            <%= form.label :amenities %>
            <%= form.text_area :amenities, class: 'form-control' %>
        </div>
    </div>

    <div class="form-group row">
        <div class="form-group col-md-3"> 
            <%= form.label :price_per_night %> 
            <%= form.text_field :price_per_night, class: 'form-control' %>
        </div>
    </div>

    <div class="form-group row">
        <div class="form-group col-md-3"> 
            <%= form.label :Gallery %> 
            <%= form.file_field :images, multiple: true %>
        </div>
    </div>
    
    <div class="form-group row">
        <div class="form-group col-md-3"> 
            <%= form.submit %>
        </div>
    </div>
<% end %>

app/views/listings/_search-results.html.erb
<div class= "card-deck" style= "display:flex; justify-content: space-between">
    <% @listings.each_with_index do |listing, index| %>
        <div class = "d-inline-block">
            <div class="card border-dark mb-4 mr-2" style="width: 18rem; text-align:center">
                <% if listing.images != [] %>
                    <div id="carouselExampleIndicators-<%= index %>" class="carousel slide w-100" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <% listing.images.each_with_index do |image, x| %>
                                <% if x == 0 %>
                                    <li data-target="#carouselExampleIndicators-<%= index %>" data-slide-to="<%= x %>" class="active"></li>
                                <% else %>
                                    <li data-target="#carouselExampleIndicators-<%= index %>" data-slide-to="<%= x %>"></li>
                                <% end %>
                            <% end %>
                        </ol>
                        <div class="carousel-inner">

                            <% listing.images.each do |image| %>
                                <% if image == listing.images[0] %>
                                    <div class="carousel-item active">
                                    <img class="d-block w-100" src=<%= image.url %>>
                                    </div>
                                <% else %>
                                    <div class="carousel-item">
                                    <img class="d-block w-100" src=<%= image.url %>>
                                    </div>
                                <% end %>
                            <% end %>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators-<%= index %>" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators-<%= index %>" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= listing.property_name %></h5>
                        <h5 class="card-title"><%= listing.property_type %></h5>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"> RM <%= listing.price_per_night %> per night</li>
                        </ul> <br/>
                        <%= link_to 'View property', listing_path(listing), class:"btn btn-primary" %>
                    </div>
                    <div class="card-footer">
                        <% if listing.verification == true %>
                            <img class="card-img" style="width: 1.5rem;"src="/assets/verify-icon.png" alt="Card image cap">
                        <% end %>
                    </div>
                <% else %>
                    <div class="card-body">
                        <h5 class="card-title"><%= listing.property_name %></h5>
                        <h5 class="card-title"><%= listing.property_type %></h5>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"> RM <%= listing.price_per_night %> per night</li>
                        </ul> <br/>
                        <%= link_to 'View property', listing_path(listing), class:"btn btn-primary" %>
                    </div>
                    <div class="card-footer">
                        <% if listing.verification == true %>
                            <img class="card-img" style="width: 1.5rem;"src="/assets/verify-icon.png" alt="Card image cap">
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/listings/edit.html.erb
<h1> Edit Listing </h1>

<%= render partial: '/listings/form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>All listings</h1>

<%= form_with scope: @listing, url:listings_path, method: :get, class:'form-inline my-2 my-lg-0' , remote: true do |form| %>
          <%= form.text_field :omnisearch, class: "form-control mr-sm-2" %>
          <%= form.submit "search", class:"btn btn-outline-success my-2 my-sm-0" %>
<% end %>

<br/>

<div id="search-results" > 
    <%= render partial: '/listings/search-results' %>
</div>

app/views/listings/index.js.erb
$("#search-results").html("<%= j render 'search-results' %>");

app/views/listings/my_listings.html.erb
<h1>All my listings</h1>
 
<%= render partial: '/listings/search-results' %>

<%= link_to 'Back', listings_path %>

app/views/listings/new.html.erb
<h1> New Listing </h1>

<%= render partial: '/listings/form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<% if @reservation.errors.any? %>
    <div id="error_explanation">
    <h2>
        <%= pluralize(@reservation.errors.count, "error") %> prohibited
        this reservation from being saved:
    </h2>
    <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
<% end %>

<div id="carouselExampleIndicators" class="carousel slide w-100" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">

    <% @listing.images.each do |image| %>
      <% if image == @listing.images[0] %>
        <div class="carousel-item active">
          <img class="d-block w-100" src=<%= image.url %>>
        </div>
      <% else %>
        <div class="carousel-item">
          <img class="d-block w-100" src=<%= image.url %>>
        </div>
      <% end %>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<h2> Property Information:</h2>
<p>
  <strong>Property type:</strong>
  <%= @listing.property_type %>
</p>
 
<p>
  <strong>Property name:</strong>
  <%= @listing.property_name %>
</p>
 
<p>
  <strong>Country:</strong>
  <%= @listing.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @listing.zipcode %>
</p>

<p>
  <strong> Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Number of guests:</strong>
  <%= @listing.no_of_guests %>
</p>

<p>
  <strong>Number of bedrooms:</strong>
  <%= @listing.no_of_bedrooms %>
</p>
 
<p>
  <strong>Number of beds:</strong>
  <%= @listing.no_of_beds %>
</p>

<p>
  <strong>Number of bathrooms:</strong>
  <%= @listing.no_of_bathrooms %>
</p>
 
<p>
  <strong>Amenities:</strong>
  <%= @listing.amenities %>
</p>

<p>
  <strong>Price per night:</strong>
  <%= @listing.price_per_night %>
</p>

<% if @listing.verification == true %>
  <p><i> Listing already verified </i></p>
<% else %>
  <% if current_user.superadmin? || current_user.moderator? %>
  <%= link_to 'Verify listing', verify_listing_path(@listing) %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_listing_path(@listing) %>
<%= link_to 'Back', listings_path %>
<%= link_to 'Delete', listing_path(@listing), method: :delete, data: { confirm: 'Are you sure?'} %>

<br/>

<nav class="navbar fixed-bottom navbar-light bg-faded">
  <img class="card-img" style="width: 5rem;"src="/assets/airbnb.jpg" alt="Card image cap">

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Book now!
  </button>
</nav>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Book now before it's gone!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <%= form_with scope: :reservation, url: listing_reservations_path(@listing.id), local: true do |form| %>
            <div class="form-group row">
              <div class="form-group col-md-6">
                  <%= form.label :check_in %>
                  <%= form.date_field :check_in, class: 'form-control' %>
              </div>
              <div class="form-group col-md-6">
                    <%= form.label :check_out %>
                    <%= form.date_field :check_out, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group row">
                <div class="form-group col-md-12">
                    <%= form.label :no_of_guests %> <br/>
                    <%= form.text_field :no_of_guests, class: 'form-control' %>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Book</button>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>