config/routes.rb
Rails.application.routes.draw do
  get 'reservation/:reservation_id/braintree/new' => "braintree#new", as: "braintree_new"
  get 'welcome/index'
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings

  resources :listings do
    resources :reservations
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/mylistings" => "listings#my_listings", as: "my_listings"
  get "/listings/:id/verify" => "listings#verify_listing", as: "verify_listing"

  post "/reservation/:id/braintree/checkout" => "braintree#checkout", as: "total_price_braintree_checkout" 
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :authentications, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :reservations, dependent: :destroy

  enum status: { customer: 0, moderator: 1, superadmin: 2 }
  mount_uploader :avatar, AvatarUploader

  def self.create_with_auth_and_hash(authentication, auth_hash)
      user = self.create!(
      first_name: auth_hash["info"]["name"].split(" ")[0],
      last_name: auth_hash["info"]["name"].split(" ")[1],
      email: auth_hash["info"]["email"],
      password: SecureRandom.hex(10)
    )
    user.authentications << authentication
    return user
  end

  # grab google to access google for user data
  def google_token
    x = self.authentications.find_by(provider: 'google_oauth2')
    return x.token unless x.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

    def show
      @user = current_user
      @reservations = Reservation.all
    end

    def edit
      @listing = Listing.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      @user.update(user_params)
      redirect_to @user 
    end

    def user_from_params
      email = user_params.delete(:email)
      password = user_params.delete(:password)
      first_name = user_params.delete(:first_name)
      last_name = user_params.delete(:last_name)
      gender = user_params.delete(:gender)
      
      Clearance.configuration.user_model.new(user_params).tap do |user|
        user.email = email
        user.password = password
        user.first_name = first_name
        user.last_name = last_name
        user.gender = gender
      end
    end

    def user_params
      params.require(:user).permit(
        :first_name, 
        :last_name, 
        :email, 
        :password,
        :gender,
        :birthday,
        :phone_number,
        :description, 
        :avatar
        )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user, :html => {:multipart => true} do |form| %>
    <div class="form-group row">
      <div class="form-group col-md-6">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>
      <div class="form-group col-md-6">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="form-group col-md-6">
        <%= form.label :email %>
        <%= form.text_field :email, type: 'email', class: 'form-control' %>
      </div>
      <div class="form-group col-md-6">
        <%= form.label :password %>
        <%= form.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="form-group col-md-4">
        <%= form.label :gender %>
        <%= form.text_field :gender, class: 'form-control' %>
      </div>
      <div class="form-group col-md-4">
        <%= form.label :birthday %>
        <%= form.date_field :birthday, class: 'form-control' %>
      </div>
      <div class="form-group col-md-4">
        <%= form.label :phone_number %>
        <%= form.text_field :phone_number, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="form-group col-md-12">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-3"> 
            <%= form.file_field :avatar %>
        </div>
    </div>
    <div class="form-group row">
        <div class="form-group col-md-3"> 
            <%= form.submit %>
        </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1> Edit your details. </h1>

<%= render partial: '/users/form' %>

<%= link_to 'Back', user_path %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row" >
        <div class= "col-sm-4">
            <h1> Profile </h1> 

            <div class="card border-dark mb-3" style="width: 20rem;">
                <img class="card-img-top" src=<%= @user.avatar_url %> alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title"><%= " #{@user.first_name} #{@user.last_name} "%></h5>
                    <h5 class="card-title">Email: <%= @user.email %></h5>
                    <h5 class="card-title">Gender: <%= @user.gender %></h5>
                    <h5 class="card-title">D.O.B: <%= @user.birthday %></h5>
                    <h5 class="card-title">Phone number: <%= @user.phone_number %></h5>
                    <h5 class="card-title">Bio: <%= @user.description %></h5>

                    <% if @user.id = current_user.id %>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                            Edit details
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">User Details</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <%= form_with model: @user, :html => {:multipart => true} do |form| %>
                                        <div class= "form-group row">
                                            <div class="form-group col-md-6">
                                                <%= form.label :first_name %>
                                                <%= form.text_field :first_name, class: 'form-control' %>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <%= form.label :last_name %>
                                                <%= form.text_field :last_name, class: 'form-control' %>
                                            </div>
                                        </div>
                                        <div class= "form-group row">
                                            <div class="form-group col-md-5">
                                                <%= form.label :gender %>
                                                <%= form.select 'gender', options_for_select(['(select one)', 'Male', 'Female'], '1'), { prompt: true }, required: true, class: 'form-control' %>
                                            </div>
                                            <div class="form-group col-md-7">
                                                <%= form.label :birthday %>
                                                <%= form.date_field :birthday, class: 'form-control' %>
                                            </div>
                                        </div>
                                        <div class= "form-group row">
                                            <div class="form-group col-md-5">
                                                <%= form.label :phone_number %>
                                                <%= form.text_field :phone_number, class: 'form-control' %>
                                            </div>
                                        </div>
                                        <div class= "form-group row">
                                            <div class="form-group col-md-12">
                                                <%= form.label :description %>
                                                <%= form.text_area :description, class: 'form-control' %>
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-md-3"> 
                                                <%= form.label :profile_pic %>
                                                <%= form.file_field :avatar %>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>

    <div class= "col-sm-8">
        <h1> Reservations </h1>

        <% @reservations.each do |reservation| %>
            <div class = "d-inline-block">
                <div class="card border-dark mb-4 mr-2" style="width: 18rem; text-align:center;">
                    <img class="card-img-top" src=<%= reservation.listing.images.first.to_s %> alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title"><%= reservation.listing.property_name %></h5>
                        <h5 class="card-title"><%= reservation.listing.property_type %></h5>
                        <h6 class="card-subtitle mb-2 text-muted"><%= reservation.check_in %> - <%= reservation.check_out %> </h6>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"> RM <%= reservation.total_price %> </li>
                        </ul>
                        <div class="btn btn-primary">
                        <%= link_to 'View property', listing_path(reservation.listing) %>
                        <%= link_to 'Delete', listing_reservation_path(reservation.listing), method: :delete, data: { confirm: 'Are you sure?'} %>
                        </div>

                    </div>
                    <div class="card-footer">
                        <% if reservation.listing.verification == true %>
                            <img class="card-img" style="width: 1.5rem;"src="/assets/verify-icon.png" alt="Card image cap">
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>