config/routes.rb
Rails.application.routes.draw do
  get 'reservation/:reservation_id/braintree/new' => "braintree#new", as: "braintree_new"
  get 'welcome/index'
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings

  resources :listings do
    resources :reservations
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/mylistings" => "listings#my_listings", as: "my_listings"
  get "/listings/:id/verify" => "listings#verify_listing", as: "verify_listing"

  post "/reservation/:id/braintree/checkout" => "braintree#checkout", as: "total_price_braintree_checkout" 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,700" rel="stylesheet">
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'%>
  <%= javascript_include_tag "https://code.jquery.com/jquery-3.2.1.slim.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" %>
  <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js' %>
  
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  
 <%= csrf_meta_tag %>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <img class="card-img" style="width: 5rem;"src="/assets/airbnb.jpg" alt="Card image cap">
    <a class="navbar-brand" href="/">AirBnB</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <%= form_with scope: @listing, url:listings_path, method: :get, class:'form-inline my-2 my-lg-0' , local: true do |form| %>
          <%= form.text_field :omnisearch, class: "form-control mr-sm-2" %>
          <%= form.submit "search", class:"btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
      
      <ul class="ml-auto navbar-nav smt-lg-0">
        <% if signed_in? -%>
            <li class="nav-item active">
              <div class="nav-link">
                <%= link_to t(".home"), welcome_index_path %>
              </div>
            </li>
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to t(".profile"), user_path(current_user) %>
              </div>
            </li>
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to t(".start_hosting"), new_listing_path %>  
              </div>
            </li>
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to t(".all_listings"), listings_path %>  
              </div>
            </li>
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to t(".all_my_listings"), my_listings_path %>  
              </div>
            </li>
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
              </div>
            </li>
            <li class="nav-item dropdown">
              <img class="nav-link dropdown-toggle" src=<%= current_user.avatar.url %> style="width: 4rem; border-radius: 5px;"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <div class="dropdown-item" >
                      <%= link_to t(".profile"), user_path(current_user) %>
                  </div>
                  <div class="dropdown-item" >
                      <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
                  </div>
                </div>
            </li>
        <% else -%>
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to t(".sign_up"), sign_up_path %>  
              </div>          
            </li>
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to t(".sign_in"), sign_in_path %>  
              </div>          
            </li>    
            <li>
              <div class="nav-link">
                <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
              </div>          
            </li>
        <% end -%>
      </ul>
    </div>
  </nav>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%= value %></div>
    <% end %>
  </div>

  <div class="container mt-2 mb-5">
    <%= yield %>
  </div>
</body>
</html>